name: Deploy Battleship Game v0

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./battleship-game/frontend

      - name: Build application
        run: npm run build
        working-directory: ./battleship-game/frontend

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./battleship-game/frontend/dist
          destination_dir: ./battleship-game/frontend
